env:
  browser: true
  es2021: true
  jest: true
  node: true
  "cypress/globals": true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - "@typescript-eslint"
  - jest
  - cypress

rules:
  "react/react-in-jsx-scope": off

overrides:
  - files: ["cypress/plugins/index.js"]
    rules:
      "@typescript-eslint/no-var-requires": off
